-- Paso 1. Crear todas las tablas vacías en la base de datos

create table team
(
  "team_id" bigint primary key,
  "full_name" varchar,
  "abbreviation" varchar,
  "nickname" varchar,
  "city" varchar,
  "state" varchar,
  "year_founded" int,
  "arena" varchar,
  "arena_capacity" int,
  "owner" varchar,
  "general_manager" varchar,
  "head_coach" varchar,
  "dleague_affiliation" varchar,
  "facebook_website_link" varchar,
  "instagram_website_link" varchar,
  "twitter_website_link" varchar
);

create table player
(
  "player_id" bigint primary key,
  "first_name" varchar,
  "last_name" varchar,
  "full_name" varchar,
  "is_active" boolean,
  "birthdate" date,
  "school" varchar,
  "country" varchar,
  "last_affiliation" varchar,
  "height" varchar,
  "weight" numeric,
  "season_exp" int,
  "jersey" varchar,
  "position" varchar,
  "roster_status" varchar,
  "from_year" int,
  "to_year" int,
  "dleague_flag" boolean,
  "nba_flag" boolean,
  "games_played_flag" boolean,
  "all_star_appearances" int,
  "team_id" bigint
);

create table team_history
(
  "team_history_id" BIGINT generated by default as identity primary key,
  "team_id" bigint not null,
  "city" varchar,
  "nickname" varchar,
  "year_founded" int,
  "year_active_till" int
);

create table team_salary
(
  "team_id" bigint not null,
  "season" varchar not null,
  "salary" numeric,
  "source_url" varchar,
  primary key ("team_id", "season")
);

create table game
(
  "game_id" bigint primary key,
  "season_id" bigint,
  "season" varchar,
  "game_date" date,
  "home_team_id" bigint not null,
  "away_team_id" bigint not null,
  "game_status_id" int,
  "game_status_text" varchar,
  "game_code" varchar,
  "wl_home" varchar,
  "wl_away" varchar,
  "min_home" int,
  "min_away" int,
  "fgm_home" int,
  "fga_home" int,
  "fg_pct_home" numeric,
  "fg3m_home" int,
  "fg3a_home" int,
  "fg3_pct_home" numeric,
  "ftm_home" int,
  "fta_home" int,
  "ft_pct_home" numeric,
  "oreb_home" int,
  "dreb_home" int,
  "reb_home" int,
  "ast_home" int,
  "stl_home" int,
  "blk_home" int,
  "tov_home" int,
  "pf_home" int,
  "pts_home" int,
  "plus_minus_home" numeric,
  "fgm_away" int,
  "fga_away" int,
  "fg_pct_away" numeric,
  "fg3m_away" int,
  "fg3a_away" int,
  "fg3_pct_away" numeric,
  "ftm_away" int,
  "fta_away" int,
  "ft_pct_away" numeric,
  "oreb_away" int,
  "dreb_away" int,
  "reb_away" int,
  "ast_away" int,
  "stl_away" int,
  "blk_away" int,
  "tov_away" int,
  "pf_away" int,
  "pts_away" int,
  "plus_minus_away" numeric,
  "pts_paint_home" int,
  "pts_2nd_chance_home" int,
  "pts_fast_break_home" int,
  "largest_lead_home" int,
  "lead_changes_home" int,
  "times_tied_home" int,
  "team_turnovers_home" int,
  "total_turnovers_home" int,
  "team_rebounds_home" int,
  "pts_off_turnovers_home" int,
  "pts_paint_away" int,
  "pts_2nd_chance_away" int,
  "pts_fast_break_away" int,
  "largest_lead_away" int,
  "lead_changes_away" int,
  "times_tied_away" int,
  "team_turnovers_away" int,
  "total_turnovers_away" int,
  "team_rebounds_away" int,
  "pts_off_turnovers_away" int,
  "pts_qtr1_home" int,
  "pts_qtr2_home" int,
  "pts_qtr3_home" int,
  "pts_qtr4_home" int,
  "pts_ot1_home" int,
  "pts_ot2_home" int,
  "pts_ot3_home" int,
  "pts_ot4_home" int,
  "pts_ot5_home" int,
  "pts_ot6_home" int,
  "pts_ot7_home" int,
  "pts_ot8_home" int,
  "pts_ot9_home" int,
  "pts_ot10_home" int,
  "pts_qtr1_away" int,
  "pts_qtr2_away" int,
  "pts_qtr3_away" int,
  "pts_qtr4_away" int,
  "pts_ot1_away" int,
  "pts_ot2_away" int,
  "pts_ot3_away" int,
  "pts_ot4_away" int,
  "pts_ot5_away" int,
  "pts_ot6_away" int,
  "pts_ot7_away" int,
  "pts_ot8_away" int,
  "pts_ot9_away" int,
  "pts_ot10_away" int,
  "attendance" int,
  "game_time" varchar
);

create table player_salary
(
  "salary_id" BIGINT generated by default as identity primary key,
  "player_id" bigint not null,
  "team_id" bigint,
  "season" varchar not null,
  "salary" numeric,
  "status" varchar,
  "contract_detail" varchar,
  "is_final_season" boolean,
  "is_waived" boolean,
  "is_on_roster" boolean,
  "is_non_guaranteed" boolean,
  "is_team_option" boolean,
  "is_player_option" boolean
);

create table draft
(
  "draft_year" int not null,
  "pick_overall" int not null,
  "round_number" int,
  "round_pick" int,
  "player_id" bigint,
  "team_id" bigint,
  "organization_from" varchar,
  "organization_type" varchar,
  "organization_type_slug" varchar,
  "organization_location" varchar,
  primary key ("draft_year", "pick_overall")
);

create table game_inactive_player
(
  "game_id" bigint not null,
  "player_id" bigint not null,
  "team_id" bigint,
  "jersey_num" varchar,
  primary key ("game_id", "player_id")
);

create table official
(
  "official_id" bigint primary key,
  "first_name" varchar,
  "last_name" varchar,
  "jersey_num" varchar
);

create table game_official
(
  "game_id" bigint not null,
  "official_id" bigint not null,
  primary key ("game_id", "official_id")
);

create table player_season_stats
(
    player_season_stats_id BIGINT
        generated by default as identity
        primary key,

    player_id bigint not null,
    team_id bigint,
    season varchar not null,

    gp int,
    min numeric,

    pts numeric,
    ast numeric,
    reb numeric,
    stl numeric,
    blk numeric,

    fg_pct numeric,
    fg3_pct numeric,
    ft_pct numeric,

    plus_minus numeric,

    foreign key (player_id)
        references player (player_id),

    foreign key (team_id)
        references team (team_id)
);

alter table player add foreign key ("team_id") references team ("team_id");
alter table team_history add foreign key ("team_id") references team ("team_id");
alter table team_salary add foreign key ("team_id") references team ("team_id");
alter table game add foreign key ("home_team_id") references team ("team_id");
alter table game add foreign key ("away_team_id") references team ("team_id");
alter table player_salary add foreign key ("player_id") references player ("player_id");
alter table player_salary add foreign key ("team_id") references team ("team_id");
alter table draft add foreign key ("player_id") references player ("player_id");
alter table draft add foreign key ("team_id") references team ("team_id");
alter table game_inactive_player add foreign key ("game_id") references game ("game_id");
alter table game_inactive_player add foreign key ("player_id") references player ("player_id");
alter table game_inactive_player add foreign key ("team_id") references team ("team_id");
alter table game_official add foreign key ("game_id") references game ("game_id");
alter table game_official add foreign key ("official_id") references official ("official_id");